#################
####  LOCAL  ####
#################
spring:
  config:
    activate:
      on-profile: local
  application:
    name: admin
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ENC(z0E3pVgdYTl8xTsqcbpggeQ/BaMXhChyeMTarbk3bSvirnupXdEzbLHR+zCD0+BqFWyqryeiFFc=)
    username: ENC(zjtt39UJAPnH8koc9erOsw==)
    password: ENC(RtOuXeSNC8cQUNXmddy4Q70a9uH9XWbZ)

#jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

jwt:
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
