#################
####   PROD  ####
#################
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: admin
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ENC(z0E3pVgdYTl8xTsqcbpggeQ/BaMXhChyeMTarbk3bSvirnupXdEzbLHR+zCD0+BqFWyqryeiFFc=)
    username: ENC(zjtt39UJAPnH8koc9erOsw==)
    password: ENC(RtOuXeSNC8cQUNXmddy4Q70a9uH9XWbZ)

#jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor