#################
####   DEV   ####
#################
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: user
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(8yQYQKOpNfdwQmxx9ru5Xkj9z3J271WeK0OlkauvkUuK5bfuUoRdIWUrjnVJ64jylQ++839VeBjBvJy2iWYVKA==)
    username: ENC(zjtt39UJAPnH8koc9erOsw==)
    password: ENC(RtOuXeSNC8cQUNXmddy4Q70a9uH9XWbZ)

#jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

#  servlet:
#    multipart:
#      enabled: false
# KUPLOAD
license:
  product_key: PHK8U-8062-86LU-FYF11
  license_key: yvPknayZnuh9lQ51mSVzkywwqRvVt+MlOnWSSAWbRnMbRAWsZnWfPA9gSAMOJAWALnMkKhTKMkuYQjuLY2xZGkOO2gB82wsJdnWOFAMXZn9wFnWkHnWjJn9aHhZ0E0DMEsV5gfeJkGETkGZWtXvUluhUtXdUlRpZlxhZlulkzzilx5avt8lkyUYWlud5kxh6kxhXtXdUlxO=

setting:
  runtimes: 3
  width: 800
  height: 600
  skin_name: default
  lang: ko
  mode: production

uploader_setting:
  develop_language: JAVA

server:
  compression:
    enabled: true
    mime-types: text/html

logging:
  level:
    jdbc:
      resultset: warn
      audit: warn
      connection: warn
      sqlonly: off